apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  labels:
    openshift.gitops/environment: dev
  name: dev-bootstrap
  namespace: argocd
spec:
  syncPolicy:
    preserveResourcesOnDeletion: true
  generators:
  - list:
      elements:
      - applicationurl: https://github.com/dordavid015/argo.git
        apppath: template-design/bootstrap
        apptargetrevision: main
        valuesfiles: '/template-design/clusters/dev/dev-bootstrap-values.yaml'
        appname: dev-cluster-bootstrap-components
      - applicationurl: https://github.com/dordavid015/argo.git
        apppath: template-design/paas
        apptargetrevision: main
        valuesfiles: '/template-design/clusters/dev/dev-paas-values.yaml'
        appname: dev-cluster-paas-components
  template:
    metadata:
      name: '{{ appname }}'  # שם ידרוס את השם הקודם אם יש
    spec:
      project: default
      source:
        path: '{{ apppath }}'
        repoURL: '{{ applicationurl }}'
        targetRevision: '{{ apptargetrevision }}'
        helm:
          valueFiles:
          - '{{ valuesfiles }}'  # העברת קובץ ה-Values המתאים
      destination:
        server: https://kubernetes.default.svc
        namespace: dor
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - preserveResourceOnDeletion=true
          - CreateNamespace=false
          - PruneLast=false
          - ApplyOutOfSyncOnly=true
          - Replace=false
